stages:
  - deploy
  - build-site
  - docker-deploy

deploy build_site:
    stage: build-site
    only:
    - schedules
    script:
    - cd website && hugo --minify -d ../public && cd ..
    - git config remote.aideqcdeploy.url >&- || git remote add -t master aideqcdeploy https://amccaskey:$AIDEQC_ACCESS_TOKEN@github.com/aide-qc/deploy
    - cp -r public/* . && rm -rf public 
    - git status
    - git add background categories css developers getting_started js tags users *.html *.xml *.png 
    - git status
    - export n_changes=$(git diff --cached --numstat | wc -l)
    - if [ "$n_changes" -gt "0" ]; then git commit -m "updating aide-qc software docs page" && git push -f aideqcdeploy HEAD:master && git remote remove aideqcdeploy ; else echo "Ran the else statement, no files to upload." ; fi

docker run_docker_deploy_xacc_bionic:
  stage: deploy
  only:
   - schedules
  script:
  - cd docker/xacc/debian/bionic && sh build.sh 
  - docker system prune -f
  - docker rmi -f xacc/bionic 

docker run_docker_deploy_xacc_focal:
  stage: deploy
  only:
   - schedules
  script:
  - cd docker/xacc/debian/focal && sh build.sh
  - docker system prune -f
  - docker rmi -f xacc/focal 

docker run_docker_deploy_qcor_bionic:
  stage: deploy
  only:
   - schedules
  script:
  - cd docker/qcor/debian/bionic && sh build.sh 
  - docker system prune -f 
  - docker rmi -f qcor/bionic 

docker run_docker_deploy_qcor_focal:
  stage: deploy
  only:
   - schedules
  script:
  - cd docker/qcor/debian/focal && sh build.sh 
  - docker system prune -f 
  - docker rmi -f qcor/bionic 

docker run_docker_deploy:
  stage: docker-deploy
  only:
   - schedules
  script:
  - cd docker/deploy/dev && docker build -t qcor/qcor . --no-cache
  - echo "$REGISTRY_PASSWORD" | docker login -u qcor --password-stdin
  - docker push qcor/qcor
  - docker system prune -f
  - docker rmi -f qcor/qcor 