stages:
  - deploy
  - build-site

deploy build_site:
    stage: build-site
    only:
    - master
    script:
    - cd website && hugo --minify -d ../public
    - git config remote.aideqcdeploy.url >&- || git remote add -t master aideqcdeploy https://amccaskey:$AIDEQC_ACCESS_TOKEN@github.com/aide-qc/deploy
    - cd .. && git checkout gh-pages
    - cp -r public/* . && rm -rf public 
    - git add background categories css developers getting_started js tags users website *.html *.xml *.png *.md
    - export n_changes=$(git diff --cached --numstat | wc -l)
    - if [ "$n_changes" -gt "0" ]; then git commit -m "updating aide-qc software docs page" && git push -f aideqcdeploy HEAD:gh-pages && git remote remove aideqcdeploy ; else echo "Ran the else statement, no files to upload." ; fi

docker run_docker_deploy_xacc_bionic:
  stage: deploy
  only:
   - schedules
  script:
  - cd docker/xacc/debian/bionic && sh build.sh 
  - docker system prune -f 

docker run_docker_deploy_xacc_focal:
  stage: deploy
  only:
   - schedules
  script:
  - cd docker/xacc/debian/focal && sh build.sh
  - docker system prune -f  

docker run_docker_deploy_qcor_bionic:
  stage: deploy
  only:
   - schedules
  script:
  - cd docker/qcor/debian/bionic && sh build.sh 
  - docker system prune -f 

docker run_docker_deploy_qcor_focal:
  stage: deploy
  only:
   - schedules
  script:
  - cd docker/qcor/debian/focal && sh build.sh 
  - docker system prune -f 
