name: "Build XACC Debian Package for Ubuntu 20.04 (focal)"

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run once a day
    - cron:  '30 5 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Linux CI"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: build
        working-directory: docker/xacc/debian/focal/
        run: source build_github_action.sh